name: Github Action workflow for building Multi-architecture images using Qemu user static and Buildah on native architecture
on:
  push:
    branches: multi-arch-natively

  workflow_dispatch:
env:
  QUAY_REPO: quay.io/mayurwaghmode111/gha-multi-arch
  ROBOT_USER: ${{ secrets.QUAY_USER }}
  ROBOT_TOKEN: ${{ secrets.QUAY_PWD }}
  GH_REPO: multi-arch-github

jobs:
  x86-image:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: Build amd64 image natively
        run: |
         buildah bud -f Dockerfile -t quay.io/mayurwaghmode111/gha-multi-arch:$(uname -m) .
         buildah login -u ${{ secrets.ROBOT_USER }} -p ${{ secrets.ROBOT_TOKEN }} quay.io
         podman push quay.io/mayurwaghmode111/gha-multi-arch:$(uname -m)
  ppc64le-image:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: ssh into the ppc64le machine and build the ppc64le image natively
        run: |
          rm -rf /root/$GH_REPO
          git clone -b multi-arch-natively https://github.com/mayurwaghmode/multi-arch-github.git /root/multi-arch-github
          echo -e "SSH into the Power machine and execute the script\n"
          ssh root@${{ secrets.PPC64LE_MACHINE_IP }} < /root/$GH_REPO/script-to-run-on-ppc64le.sh 
        env:
          $QUAY_REPO: quay.io/mayurwaghmode111/gha-multi-arch
          $ROBOT_USER: ${{ secrets.QUAY_USER }}
          $ROBOT_TOKEN: ${{ secrets.QUAY_PWD }}
          
      - name: Build the multi-image multi-arch manifest
        run: |
          buildah manifest create $QUAY_REPO 
          buildah manifest add $QUAY_REPO $QUAY_REPO:ppc64le
          buildah manifest add $QUAY_REPO $QUAY_REPO:x86_64
          buildah manifest inspect $QUAY_REPO
          buildah login -u ${{ secrets.ROBOT_USER }} -p ${{ secrets.ROBOT_TOKEN }} quay.io
          podman manifest push --all $QUAY_REPO $QUAY_REPO:native
          buildah manifest rm $QUAY_REPO
