name: Github Action workflow for building Multi-architecture images using Qemu user static and Buildah on native architecture
on:
  push:
    branches: multi-arch-natively

  workflow_dispatch:
env:
  QUAY_REPO: quay.io/mayurwaghmode111/gha-multi-arch
  ROBOT_USER: ${{ secrets.QUAY_USER }}
  ROBOT_TOKEN: ${{ secrets.QUAY_PWD }}
  GH_REPO: multi-arch-github

jobs:
  x86-image:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: Build amd64 image natively
        run: |
         buildah bud -f Dockerfile -t $QUAY_REPO:$(uname -m) .
         buildah login -u ${{ secrets.ROBOT_USER }} -p ${{ secrets.ROBOT_TOKEN }} quay.io
         podman push $QUAY_REPO:$(uname -m)
 
  ppc64le-image:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.PPC64LE_MACHINE_IP }}
          username: root
          privateKey: ${{ secrets.KEY}}
          script: |
            rm -rf /root/$GH_REPO
            git clone -b multi-arch-natively https://github.com/mayurwaghmode/multi-arch-github.git /root/$GH_REPO
            echo -e "SSH into the Power machine and execute the script\n"
            ./root/$GH_REPO/script-to-run-on-ppc64le.sh $QUAY_REPO $ROBOT_USER $ROBOT_TOKEN
          
  multi-arch-image:
      runs-on: self-hosted
      needs: [x86-image, ppc64le-image]
      steps:
      - uses: actions/checkout@v3 
      - name: Build and push multi-arch manifest
        run: |
          buildah manifest create $QUAY_REPO 
          buildah manifest add $QUAY_REPO $QUAY_REPO:ppc64le
          buildah manifest add $QUAY_REPO $QUAY_REPO:x86_64
          buildah manifest inspect $QUAY_REPO
          buildah login -u ${{ secrets.ROBOT_USER }} -p ${{ secrets.ROBOT_TOKEN }} quay.io
          podman manifest push --all $QUAY_REPO $QUAY_REPO:native
          buildah manifest rm $QUAY_REPO
